services:
  app:
    build: .
    environment:
      DATABASE_URL: postgres://app:app@db:5432/appdb
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    # could do persistent storage here but not needed in this app unless reviewer is fine with docker compose down -v all the time
    # volumes:
    #   - pgdata: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 5

# volumes:
#   pgdata: